version: '2.1'
services:
    # The ERP Container
    # -----------------
    # Accessing container via ssh:
    # ssh in the Container:   ssh localhost -l s3 -p 2205 -i docker_erp.key
    #
    erp-bpmn:
      image: intra.registry.abas.sh/cloud-erp-neumand1:2017r2n7
      container_name: "erp"

      ports:
      - "${SSH_TEST_PORT:-22}:22"
      - "${MINI_GUI_PORT:-8001}:80"
      - "${EDP_TEST_PORT:-6550}:6550"
      - "${GUI_TEST_PORT:-48592}:48392"

      environment:
      - ABAS_HOST=192.168.179.48
      - ABAS_GUI_PORT=${GUI_TEST_PORT:-48592}

      # The hostname is very important, especially if you intend to use `docker commit`
      user: s3
      hostname: dockerbau

    # nexus host for madep
    nexus:
      image: sonatype/nexus:oss
      container_name: "nexus"
      ports:
      - "8081:8081"
